feat : add workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,35 +6,27 @@ on:
   pull_request:
     branches: [ main ]
 
-defaults:
-  run:
-    working-directory: ./app
-
 jobs:
   # -----------------------------------------------
-  # JOB 1 — Tests et Build
+  # JOB 1 — OWASP zap : analyse faille de sécurité
   # -----------------------------------------------
   test-and-build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
+      - uses: actions/setup-node@v4
         with:
           node-version: 22
-        #   cache: 'npm'
-          cache-dependency-path: './app/package-lock.json'
+          cache: 'npm'
 
-      - name: 1. Installation
+      - name: 1. installation
         run: npm ci
 
-      - name: 2. Run Tests
+      - name: 2. run test
         run: npm run test
 
-      - name: 3. Build
+      - name: 3. build
         run: npm run build
-
   # -----------------------------------------------
   # JOB 2 — Snyk : vulnérabilités des dépendances
   # -----------------------------------------------
@@ -42,9 +34,7 @@ jobs:
     name: Snyk – Dépendances npm
     runs-on: ubuntu-latest
     needs: test-and-build
-    defaults:
-      run:
-        working-directory: ./app  # ← manquait dans votre version
+
     steps:
       - name: Checkout du code
         uses: actions/checkout@v4
@@ -53,8 +43,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 22
-          cache: 'npm'
-          cache-dependency-path: 'app/package-lock.json'
+          cache: npm
 
       - name: Installer les dépendances
         run: npm ci
@@ -62,8 +51,8 @@ jobs:
       - name: Authentification Snyk
         uses: snyk/actions/setup@master
 
-      - name: Snyk – Test des dépendances (Génération rapport)
-        run: snyk test --file=package.json --severity-threshold=high --json > snyk-report.json || true
+      - name: Snyk – Test des dépendances
+        run: snyk test --severity-threshold=high --json > snyk-report.json || true
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
@@ -71,9 +60,11 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: snyk-report
-          path: app/snyk-report.json
+          path: snyk-report.json
 
       - name: Snyk – Bloquer si critique ou élevé
-        run: snyk test --file=package.json --severity-threshold=high
+        run: snyk test --severity-threshold=high
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+          
